# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: josephlin's blog
email: josephlin117@gmail.com
description: 工人阶级没有祖国。决不能剥夺他们所没有的东西。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://josephlin.club" # the base hostname & protocol for your site
twitter_username: josephstalin117 
github_username:  josephstalin117

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
# permalink: none
permalink: /:title:output_ext