# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: josephlin
email: josephlin117@hotmail.com
description: josephlin's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://josephlin.org" # the base hostname & protocol for your site
twitter_username: josephstalin117 
github_username:  josephstalin117

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
# permalink: none
permalink: /:title:output_ext